application:
  subdomain: pandora-helper
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://pandora-helper:9000/
services:
  pandora-helper:
    # upstream: q11391/pandora-helper:latest@sha256:d2018271c6f456d092944316547bcd888dea5fe74ef6ed4a26e5d48c5a884720
    image: registry.lazycat.cloud/czyt/q11391/pandora-helper:0e797f03d0576a56
    binds:
      - /lzcapp/var/data:/app/data
    setup_script: |
      if [ ! -f /app/data/config.json ]; then
        cp /lzcapp/pkg/content/config.json /app/data/config.json
      fi
